const GET_CATEGORIES_PENDING = "GET_CATEGORIES_PENDING";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

export { GET_CATEGORIES_PENDING, GET_CATEGORIES_SUCCESS, GET_CATEGORIES_ERROR };
